name: Run all tests 

on: [push]

jobs:

  clojure:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Maven dependencies 
        uses: actions/cache@v2
        with:
    	  path: ~/.m2/repository
          key: ${{ runner.os }}-${{ hashFiles('project.clj') }}

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Install Clojure tools
        uses: DeLaGuardo/setup-clojure@3.2
        with:
          lein: latest 

      - name: Get leiningen version
        run: lein -v

      - name: Run tests
        run: lein test